In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
df_encoded = pd.get_dummies(df, columns=["mainroad", "guestroom", "basement", "hotwaterheating", "airconditioning", "prefarea", "furnishingstatus"])
df_encoded.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,...,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,False,True,True,False,...,False,True,False,False,True,False,True,True,False,False
1,12250000,8960,4,4,4,3,False,True,True,False,...,False,True,False,False,True,True,False,True,False,False
2,12250000,9960,3,2,2,2,False,True,True,False,...,True,True,False,True,False,False,True,False,True,False
3,12215000,7500,4,2,2,3,False,True,True,False,...,True,True,False,False,True,False,True,True,False,False
4,11410000,7420,4,1,2,2,False,True,False,True,...,True,True,False,False,True,True,False,True,False,False

In [4]:
np.sum(pd.isna(df_encoded) == True) # checking if any of the columns has NaN datapoints

C:\Users\mixas\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

price                              0
area                               0
bedrooms                           0
bathrooms                          0
stories                            0
parking                            0
mainroad_no                        0
mainroad_yes                       0
guestroom_no                       0
guestroom_yes                      0
basement_no                        0
basement_yes                       0
hotwaterheating_no                 0
hotwaterheating_yes                0
airconditioning_no                 0
airconditioning_yes                0
prefarea_no                        0
prefarea_yes                       0
furnishingstatus_furnished         0
furnishingstatus_semi-furnished    0
furnishingstatus_unfurnished       0
dtype: int64

In [5]:
df_encoded = df_encoded.replace({True: 1, False: 0}).astype(float)
X = df_encoded.to_numpy()
X.dtype

C:\Users\mixas\AppData\Local\Temp\ipykernel_2504\3533865153.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_encoded = df_encoded.replace({True: 1, False: 0}).astype(float)

dtype('float64')

In [6]:
X = df_encoded.drop(["price"], axis = 1)
y = df_encoded["price"]
X.shape

(545, 20)

In [7]:
# Normalizing continuos data for better predictions
mean_area = X["area"].mean()
mean_price = y.mean()
std_area = X["area"].std()
std_price = y.std()
X["area"] = (X["area"] - mean_area) / std_area
y = (y - mean_price) / std_price

In [8]:
from sklearn.model_selection import train_test_split
# Split into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
# the model only takes numpy arrays so we need to conver dataframe to array
X_train = np.asarray(X_train.T)        # (features, m)
y_train = np.asarray(y_train).reshape(1, -1)  # (1, m) for BCE/MSE

In [10]:
from nn_constructor import NeuralNetwork, Layer, LinearAct, ReluAct, MeanRegressionError

# creating layers for the model
layer1 = Layer(in_features=20, out_features=16, activation=ReluAct())
layer2 = Layer(in_features=16, out_features=8, activation=ReluAct())
layer3 = Layer(in_features=8, out_features=4, activation=ReluAct() ) 
layer4 = Layer(in_features=4, out_features=1, activation=LinearAct() ) 

# Building network
layers = [layer1, layer2, layer3, layer4]

# Initialize loss
loss = MeanRegressionError(m=X_train.shape[1], y=y_train, lamda=0.01)

# Build NeuralNetwork object
nn = NeuralNetwork(alpha=0.1, data=X_train, loss=loss, layers=layers)

nn.fit()

epoch 1 - data_loss(MSE): 0.939353 | reg_loss: 0.000618 | total: 0.939970
epoch 2 - data_loss(MSE): 0.927706 | reg_loss: 0.000618 | total: 0.928324
epoch 3 - data_loss(MSE): 0.918209 | reg_loss: 0.000618 | total: 0.918827
epoch 4 - data_loss(MSE): 0.910451 | reg_loss: 0.000618 | total: 0.911068
epoch 5 - data_loss(MSE): 0.903926 | reg_loss: 0.000618 | total: 0.904543
epoch 6 - data_loss(MSE): 0.898423 | reg_loss: 0.000618 | total: 0.899041
epoch 7 - data_loss(MSE): 0.893717 | reg_loss: 0.000618 | total: 0.894335
epoch 8 - data_loss(MSE): 0.889747 | reg_loss: 0.000618 | total: 0.890365
epoch 9 - data_loss(MSE): 0.886245 | reg_loss: 0.000618 | total: 0.886863
epoch 10 - data_loss(MSE): 0.883184 | reg_loss: 0.000618 | total: 0.883802
epoch 11 - data_loss(MSE): 0.880305 | reg_loss: 0.000618 | total: 0.880923
epoch 12 - data_loss(MSE): 0.877524 | reg_loss: 0.000618 | total: 0.878142
epoch 13 - data_loss(MSE): 0.874550 | reg_loss: 0.000618 | total: 0.875168
epoch 14 - data_loss(MSE): 0.871502 | reg_loss: 0.000618 | total: 0.872120
epoch 15 - data_loss(MSE): 0.868232 | reg_loss: 0.000618 | total: 0.868850
epoch 16 - data_loss(MSE): 0.864885 | reg_loss: 0.000618 | total: 0.865503
epoch 17 - data_loss(MSE): 0.861521 | reg_loss: 0.000618 | total: 0.862139
epoch 18 - data_loss(MSE): 0.858047 | reg_loss: 0.000618 | total: 0.858666
epoch 19 - data_loss(MSE): 0.854420 | reg_loss: 0.000618 | total: 0.855039
epoch 20 - data_loss(MSE): 0.850584 | reg_loss: 0.000618 | total: 0.851203
epoch 21 - data_loss(MSE): 0.846487 | reg_loss: 0.000618 | total: 0.847106
epoch 22 - data_loss(MSE): 0.842075 | reg_loss: 0.000619 | total: 0.842694
epoch 23 - data_loss(MSE): 0.837309 | reg_loss: 0.000619 | total: 0.837927
epoch 24 - data_loss(MSE): 0.832120 | reg_loss: 0.000619 | total: 0.832739
epoch 25 - data_loss(MSE): 0.826469 | reg_loss: 0.000619 | total: 0.827088
epoch 26 - data_loss(MSE): 0.820340 | reg_loss: 0.000619 | total: 0.820959
epoch 27 - data_loss(MSE): 0.813708 | reg_loss: 0.000619 | total: 0.814327
epoch 28 - data_loss(MSE): 0.806485 | reg_loss: 0.000619 | total: 0.807104
epoch 29 - data_loss(MSE): 0.798707 | reg_loss: 0.000620 | total: 0.799326
epoch 30 - data_loss(MSE): 0.790344 | reg_loss: 0.000620 | total: 0.790964
epoch 31 - data_loss(MSE): 0.781329 | reg_loss: 0.000620 | total: 0.781949
epoch 32 - data_loss(MSE): 0.771711 | reg_loss: 0.000620 | total: 0.772331
epoch 33 - data_loss(MSE): 0.761491 | reg_loss: 0.000621 | total: 0.762112
epoch 34 - data_loss(MSE): 0.750632 | reg_loss: 0.000621 | total: 0.751253
epoch 35 - data_loss(MSE): 0.739063 | reg_loss: 0.000621 | total: 0.739684
epoch 36 - data_loss(MSE): 0.726736 | reg_loss: 0.000622 | total: 0.727358
epoch 37 - data_loss(MSE): 0.713793 | reg_loss: 0.000622 | total: 0.714415
epoch 38 - data_loss(MSE): 0.700287 | reg_loss: 0.000622 | total: 0.700909
epoch 39 - data_loss(MSE): 0.686369 | reg_loss: 0.000623 | total: 0.686992
epoch 40 - data_loss(MSE): 0.672214 | reg_loss: 0.000623 | total: 0.672837
epoch 41 - data_loss(MSE): 0.657874 | reg_loss: 0.000624 | total: 0.658497
epoch 42 - data_loss(MSE): 0.643660 | reg_loss: 0.000624 | total: 0.644284
epoch 43 - data_loss(MSE): 0.629760 | reg_loss: 0.000625 | total: 0.630385
epoch 44 - data_loss(MSE): 0.616040 | reg_loss: 0.000625 | total: 0.616665
epoch 45 - data_loss(MSE): 0.602881 | reg_loss: 0.000625 | total: 0.603506
epoch 46 - data_loss(MSE): 0.590149 | reg_loss: 0.000626 | total: 0.590775
epoch 47 - data_loss(MSE): 0.577914 | reg_loss: 0.000626 | total: 0.578541
epoch 48 - data_loss(MSE): 0.566220 | reg_loss: 0.000627 | total: 0.566847
epoch 49 - data_loss(MSE): 0.555167 | reg_loss: 0.000627 | total: 0.555794
epoch 50 - data_loss(MSE): 0.544557 | reg_loss: 0.000628 | total: 0.545185
epoch 51 - data_loss(MSE): 0.534290 | reg_loss: 0.000628 | total: 0.534918
epoch 52 - data_loss(MSE): 0.524602 | reg_loss: 0.000628 | total: 0.525230
epoch 53 - data_loss(MSE): 0.515679 | reg_loss: 0.000629 | total: 0.516308
epoch 54 - data_loss(MSE): 0.507508 | reg_loss: 0.000629 | total: 0.508137
epoch 55 - data_loss(MSE): 0.500084 | reg_loss: 0.000629 | total: 0.500713
epoch 56 - data_loss(MSE): 0.494275 | reg_loss: 0.000630 | total: 0.494904
epoch 57 - data_loss(MSE): 0.490319 | reg_loss: 0.000630 | total: 0.490949
epoch 58 - data_loss(MSE): 0.492790 | reg_loss: 0.000630 | total: 0.493420
epoch 59 - data_loss(MSE): 0.499332 | reg_loss: 0.000631 | total: 0.499963
epoch 60 - data_loss(MSE): 0.537033 | reg_loss: 0.000630 | total: 0.537662
epoch 61 - data_loss(MSE): 0.561519 | reg_loss: 0.000631 | total: 0.562150
epoch 62 - data_loss(MSE): 0.671438 | reg_loss: 0.000629 | total: 0.672067
epoch 63 - data_loss(MSE): 0.518265 | reg_loss: 0.000631 | total: 0.518896
epoch 64 - data_loss(MSE): 0.564351 | reg_loss: 0.000629 | total: 0.564980
epoch 65 - data_loss(MSE): 0.510971 | reg_loss: 0.000631 | total: 0.511602
epoch 66 - data_loss(MSE): 0.550384 | reg_loss: 0.000629 | total: 0.551013
epoch 67 - data_loss(MSE): 0.490550 | reg_loss: 0.000631 | total: 0.491181
epoch 68 - data_loss(MSE): 0.519121 | reg_loss: 0.000630 | total: 0.519751
epoch 69 - data_loss(MSE): 0.473523 | reg_loss: 0.000631 | total: 0.474154
epoch 70 - data_loss(MSE): 0.498309 | reg_loss: 0.000630 | total: 0.498939
epoch 71 - data_loss(MSE): 0.463291 | reg_loss: 0.000632 | total: 0.463922
epoch 72 - data_loss(MSE): 0.488777 | reg_loss: 0.000630 | total: 0.489407
epoch 73 - data_loss(MSE): 0.456385 | reg_loss: 0.000632 | total: 0.457017
epoch 74 - data_loss(MSE): 0.482897 | reg_loss: 0.000631 | total: 0.483528
epoch 75 - data_loss(MSE): 0.456331 | reg_loss: 0.000632 | total: 0.456963
epoch 76 - data_loss(MSE): 0.485817 | reg_loss: 0.000631 | total: 0.486447
epoch 77 - data_loss(MSE): 0.446835 | reg_loss: 0.000632 | total: 0.447468
epoch 78 - data_loss(MSE): 0.469084 | reg_loss: 0.000631 | total: 0.469715
epoch 79 - data_loss(MSE): 0.440513 | reg_loss: 0.000633 | total: 0.441145
epoch 80 - data_loss(MSE): 0.459860 | reg_loss: 0.000631 | total: 0.460491
epoch 81 - data_loss(MSE): 0.433097 | reg_loss: 0.000633 | total: 0.433730
epoch 82 - data_loss(MSE): 0.448081 | reg_loss: 0.000631 | total: 0.448712
epoch 83 - data_loss(MSE): 0.425929 | reg_loss: 0.000633 | total: 0.426562
epoch 84 - data_loss(MSE): 0.440157 | reg_loss: 0.000631 | total: 0.440788
epoch 85 - data_loss(MSE): 0.420836 | reg_loss: 0.000633 | total: 0.421469
epoch 86 - data_loss(MSE): 0.437927 | reg_loss: 0.000631 | total: 0.438558
epoch 87 - data_loss(MSE): 0.417878 | reg_loss: 0.000633 | total: 0.418511
epoch 88 - data_loss(MSE): 0.435632 | reg_loss: 0.000631 | total: 0.436264
epoch 89 - data_loss(MSE): 0.414147 | reg_loss: 0.000633 | total: 0.414780
epoch 90 - data_loss(MSE): 0.431524 | reg_loss: 0.000632 | total: 0.432156
epoch 91 - data_loss(MSE): 0.407656 | reg_loss: 0.000633 | total: 0.408289
epoch 92 - data_loss(MSE): 0.425291 | reg_loss: 0.000632 | total: 0.425923
epoch 93 - data_loss(MSE): 0.403507 | reg_loss: 0.000633 | total: 0.404140
epoch 94 - data_loss(MSE): 0.421715 | reg_loss: 0.000632 | total: 0.422347
epoch 95 - data_loss(MSE): 0.400705 | reg_loss: 0.000633 | total: 0.401338
epoch 96 - data_loss(MSE): 0.421473 | reg_loss: 0.000632 | total: 0.422104
epoch 97 - data_loss(MSE): 0.402157 | reg_loss: 0.000634 | total: 0.402791
epoch 98 - data_loss(MSE): 0.424304 | reg_loss: 0.000632 | total: 0.424935
epoch 99 - data_loss(MSE): 0.400041 | reg_loss: 0.000634 | total: 0.400675
epoch 100 - data_loss(MSE): 0.422500 | reg_loss: 0.000632 | total: 0.423132
epoch 101 - data_loss(MSE): 0.396260 | reg_loss: 0.000634 | total: 0.396893
epoch 102 - data_loss(MSE): 0.417655 | reg_loss: 0.000632 | total: 0.418287
epoch 103 - data_loss(MSE): 0.392173 | reg_loss: 0.000634 | total: 0.392807
epoch 104 - data_loss(MSE): 0.414015 | reg_loss: 0.000632 | total: 0.414647
epoch 105 - data_loss(MSE): 0.390148 | reg_loss: 0.000634 | total: 0.390782
epoch 106 - data_loss(MSE): 0.411979 | reg_loss: 0.000632 | total: 0.412611
epoch 107 - data_loss(MSE): 0.395220 | reg_loss: 0.000634 | total: 0.395854
epoch 108 - data_loss(MSE): 0.419805 | reg_loss: 0.000632 | total: 0.420436
epoch 109 - data_loss(MSE): 0.393517 | reg_loss: 0.000634 | total: 0.394150
epoch 110 - data_loss(MSE): 0.414215 | reg_loss: 0.000632 | total: 0.414847
epoch 111 - data_loss(MSE): 0.392392 | reg_loss: 0.000634 | total: 0.393026
epoch 112 - data_loss(MSE): 0.413843 | reg_loss: 0.000632 | total: 0.414474
epoch 113 - data_loss(MSE): 0.389589 | reg_loss: 0.000634 | total: 0.390223
epoch 114 - data_loss(MSE): 0.408543 | reg_loss: 0.000632 | total: 0.409175
epoch 115 - data_loss(MSE): 0.385116 | reg_loss: 0.000634 | total: 0.385749
epoch 116 - data_loss(MSE): 0.403186 | reg_loss: 0.000632 | total: 0.403818
epoch 117 - data_loss(MSE): 0.382086 | reg_loss: 0.000634 | total: 0.382719
epoch 118 - data_loss(MSE): 0.399343 | reg_loss: 0.000632 | total: 0.399975
epoch 119 - data_loss(MSE): 0.382146 | reg_loss: 0.000634 | total: 0.382779
epoch 120 - data_loss(MSE): 0.400557 | reg_loss: 0.000632 | total: 0.401189
epoch 121 - data_loss(MSE): 0.382541 | reg_loss: 0.000634 | total: 0.383174
epoch 122 - data_loss(MSE): 0.402857 | reg_loss: 0.000632 | total: 0.403489
epoch 123 - data_loss(MSE): 0.380401 | reg_loss: 0.000634 | total: 0.381035
epoch 124 - data_loss(MSE): 0.399911 | reg_loss: 0.000632 | total: 0.400542
epoch 125 - data_loss(MSE): 0.378184 | reg_loss: 0.000634 | total: 0.378818
epoch 126 - data_loss(MSE): 0.397019 | reg_loss: 0.000632 | total: 0.397650
epoch 127 - data_loss(MSE): 0.375708 | reg_loss: 0.000634 | total: 0.376342
epoch 128 - data_loss(MSE): 0.393727 | reg_loss: 0.000632 | total: 0.394359
epoch 129 - data_loss(MSE): 0.374077 | reg_loss: 0.000634 | total: 0.374710
epoch 130 - data_loss(MSE): 0.391850 | reg_loss: 0.000632 | total: 0.392481
epoch 131 - data_loss(MSE): 0.372509 | reg_loss: 0.000634 | total: 0.373143
epoch 132 - data_loss(MSE): 0.390034 | reg_loss: 0.000632 | total: 0.390665
epoch 133 - data_loss(MSE): 0.370463 | reg_loss: 0.000634 | total: 0.371096
epoch 134 - data_loss(MSE): 0.388681 | reg_loss: 0.000632 | total: 0.389312
epoch 135 - data_loss(MSE): 0.369005 | reg_loss: 0.000634 | total: 0.369638
epoch 136 - data_loss(MSE): 0.387611 | reg_loss: 0.000632 | total: 0.388243
epoch 137 - data_loss(MSE): 0.367664 | reg_loss: 0.000634 | total: 0.368298
epoch 138 - data_loss(MSE): 0.386278 | reg_loss: 0.000632 | total: 0.386909
epoch 139 - data_loss(MSE): 0.366078 | reg_loss: 0.000634 | total: 0.366712
epoch 140 - data_loss(MSE): 0.383828 | reg_loss: 0.000632 | total: 0.384460
epoch 141 - data_loss(MSE): 0.363802 | reg_loss: 0.000634 | total: 0.364435
epoch 142 - data_loss(MSE): 0.380798 | reg_loss: 0.000632 | total: 0.381430
epoch 143 - data_loss(MSE): 0.362378 | reg_loss: 0.000634 | total: 0.363012
epoch 144 - data_loss(MSE): 0.379212 | reg_loss: 0.000632 | total: 0.379843
epoch 145 - data_loss(MSE): 0.361049 | reg_loss: 0.000634 | total: 0.361683
epoch 146 - data_loss(MSE): 0.377751 | reg_loss: 0.000632 | total: 0.378383
epoch 147 - data_loss(MSE): 0.359972 | reg_loss: 0.000634 | total: 0.360606
epoch 148 - data_loss(MSE): 0.376359 | reg_loss: 0.000632 | total: 0.376991
epoch 149 - data_loss(MSE): 0.358732 | reg_loss: 0.000634 | total: 0.359365
epoch 150 - data_loss(MSE): 0.375006 | reg_loss: 0.000632 | total: 0.375638
epoch 151 - data_loss(MSE): 0.357178 | reg_loss: 0.000634 | total: 0.357811
epoch 152 - data_loss(MSE): 0.372121 | reg_loss: 0.000632 | total: 0.372753
epoch 153 - data_loss(MSE): 0.355057 | reg_loss: 0.000634 | total: 0.355691
epoch 154 - data_loss(MSE): 0.370557 | reg_loss: 0.000632 | total: 0.371189
epoch 155 - data_loss(MSE): 0.354660 | reg_loss: 0.000634 | total: 0.355294
epoch 156 - data_loss(MSE): 0.370836 | reg_loss: 0.000632 | total: 0.371468
epoch 157 - data_loss(MSE): 0.355019 | reg_loss: 0.000634 | total: 0.355652
epoch 158 - data_loss(MSE): 0.372699 | reg_loss: 0.000632 | total: 0.373330
epoch 159 - data_loss(MSE): 0.353858 | reg_loss: 0.000634 | total: 0.354491
epoch 160 - data_loss(MSE): 0.371344 | reg_loss: 0.000632 | total: 0.371976
epoch 161 - data_loss(MSE): 0.353353 | reg_loss: 0.000634 | total: 0.353987
epoch 162 - data_loss(MSE): 0.371118 | reg_loss: 0.000632 | total: 0.371749
epoch 163 - data_loss(MSE): 0.352633 | reg_loss: 0.000634 | total: 0.353266
epoch 164 - data_loss(MSE): 0.370550 | reg_loss: 0.000632 | total: 0.371182
epoch 165 - data_loss(MSE): 0.351570 | reg_loss: 0.000634 | total: 0.352203
epoch 166 - data_loss(MSE): 0.369781 | reg_loss: 0.000632 | total: 0.370412
epoch 167 - data_loss(MSE): 0.350096 | reg_loss: 0.000634 | total: 0.350730
epoch 168 - data_loss(MSE): 0.367890 | reg_loss: 0.000632 | total: 0.368521
epoch 169 - data_loss(MSE): 0.348094 | reg_loss: 0.000634 | total: 0.348728
epoch 170 - data_loss(MSE): 0.365013 | reg_loss: 0.000632 | total: 0.365644
epoch 171 - data_loss(MSE): 0.346040 | reg_loss: 0.000634 | total: 0.346673
epoch 172 - data_loss(MSE): 0.361946 | reg_loss: 0.000632 | total: 0.362577
epoch 173 - data_loss(MSE): 0.344942 | reg_loss: 0.000634 | total: 0.345576
epoch 174 - data_loss(MSE): 0.360755 | reg_loss: 0.000632 | total: 0.361387
epoch 175 - data_loss(MSE): 0.343866 | reg_loss: 0.000634 | total: 0.344500
epoch 176 - data_loss(MSE): 0.359788 | reg_loss: 0.000632 | total: 0.360420
epoch 177 - data_loss(MSE): 0.342817 | reg_loss: 0.000634 | total: 0.343450
epoch 178 - data_loss(MSE): 0.357877 | reg_loss: 0.000632 | total: 0.358509
epoch 179 - data_loss(MSE): 0.341668 | reg_loss: 0.000633 | total: 0.342301
epoch 180 - data_loss(MSE): 0.356599 | reg_loss: 0.000632 | total: 0.357231
epoch 181 - data_loss(MSE): 0.340740 | reg_loss: 0.000633 | total: 0.341374
epoch 182 - data_loss(MSE): 0.355243 | reg_loss: 0.000632 | total: 0.355875
epoch 183 - data_loss(MSE): 0.341477 | reg_loss: 0.000633 | total: 0.342111
epoch 184 - data_loss(MSE): 0.357659 | reg_loss: 0.000631 | total: 0.358291
epoch 185 - data_loss(MSE): 0.342991 | reg_loss: 0.000633 | total: 0.343625
epoch 186 - data_loss(MSE): 0.360683 | reg_loss: 0.000631 | total: 0.361314
epoch 187 - data_loss(MSE): 0.343756 | reg_loss: 0.000633 | total: 0.344389
epoch 188 - data_loss(MSE): 0.362106 | reg_loss: 0.000631 | total: 0.362737
epoch 189 - data_loss(MSE): 0.343726 | reg_loss: 0.000633 | total: 0.344360
epoch 190 - data_loss(MSE): 0.361829 | reg_loss: 0.000631 | total: 0.362461
epoch 191 - data_loss(MSE): 0.343026 | reg_loss: 0.000633 | total: 0.343659
epoch 192 - data_loss(MSE): 0.360913 | reg_loss: 0.000631 | total: 0.361544
epoch 193 - data_loss(MSE): 0.342168 | reg_loss: 0.000633 | total: 0.342802
epoch 194 - data_loss(MSE): 0.359653 | reg_loss: 0.000631 | total: 0.360284
epoch 195 - data_loss(MSE): 0.341848 | reg_loss: 0.000633 | total: 0.342481
epoch 196 - data_loss(MSE): 0.358206 | reg_loss: 0.000631 | total: 0.358838
epoch 197 - data_loss(MSE): 0.340213 | reg_loss: 0.000633 | total: 0.340846
epoch 198 - data_loss(MSE): 0.355616 | reg_loss: 0.000631 | total: 0.356247
epoch 199 - data_loss(MSE): 0.340297 | reg_loss: 0.000633 | total: 0.340930
epoch 200 - data_loss(MSE): 0.355940 | reg_loss: 0.000631 | total: 0.356571
epoch 201 - data_loss(MSE): 0.339704 | reg_loss: 0.000633 | total: 0.340338
epoch 202 - data_loss(MSE): 0.355131 | reg_loss: 0.000631 | total: 0.355763
epoch 203 - data_loss(MSE): 0.338587 | reg_loss: 0.000633 | total: 0.339220
epoch 204 - data_loss(MSE): 0.353504 | reg_loss: 0.000631 | total: 0.354135
epoch 205 - data_loss(MSE): 0.337071 | reg_loss: 0.000633 | total: 0.337704
epoch 206 - data_loss(MSE): 0.351255 | reg_loss: 0.000631 | total: 0.351887
epoch 207 - data_loss(MSE): 0.334753 | reg_loss: 0.000633 | total: 0.335386
epoch 208 - data_loss(MSE): 0.347755 | reg_loss: 0.000631 | total: 0.348386
epoch 209 - data_loss(MSE): 0.332255 | reg_loss: 0.000633 | total: 0.332889
epoch 210 - data_loss(MSE): 0.343951 | reg_loss: 0.000631 | total: 0.344582
epoch 211 - data_loss(MSE): 0.330106 | reg_loss: 0.000633 | total: 0.330740
epoch 212 - data_loss(MSE): 0.341631 | reg_loss: 0.000631 | total: 0.342263
epoch 213 - data_loss(MSE): 0.328904 | reg_loss: 0.000633 | total: 0.329537
epoch 214 - data_loss(MSE): 0.340214 | reg_loss: 0.000631 | total: 0.340846
epoch 215 - data_loss(MSE): 0.327919 | reg_loss: 0.000633 | total: 0.328552
epoch 216 - data_loss(MSE): 0.340491 | reg_loss: 0.000631 | total: 0.341122
epoch 217 - data_loss(MSE): 0.328367 | reg_loss: 0.000633 | total: 0.329000
epoch 218 - data_loss(MSE): 0.342466 | reg_loss: 0.000631 | total: 0.343097
epoch 219 - data_loss(MSE): 0.330355 | reg_loss: 0.000633 | total: 0.330988
epoch 220 - data_loss(MSE): 0.346097 | reg_loss: 0.000631 | total: 0.346728
epoch 221 - data_loss(MSE): 0.332280 | reg_loss: 0.000633 | total: 0.332913
epoch 222 - data_loss(MSE): 0.350289 | reg_loss: 0.000631 | total: 0.350920
epoch 223 - data_loss(MSE): 0.334306 | reg_loss: 0.000633 | total: 0.334940
epoch 224 - data_loss(MSE): 0.354535 | reg_loss: 0.000631 | total: 0.355166
epoch 225 - data_loss(MSE): 0.335558 | reg_loss: 0.000633 | total: 0.336192
epoch 226 - data_loss(MSE): 0.356715 | reg_loss: 0.000631 | total: 0.357346
epoch 227 - data_loss(MSE): 0.336283 | reg_loss: 0.000633 | total: 0.336916
epoch 228 - data_loss(MSE): 0.357719 | reg_loss: 0.000631 | total: 0.358350
epoch 229 - data_loss(MSE): 0.335773 | reg_loss: 0.000633 | total: 0.336406
epoch 230 - data_loss(MSE): 0.356621 | reg_loss: 0.000631 | total: 0.357252
epoch 231 - data_loss(MSE): 0.334274 | reg_loss: 0.000633 | total: 0.334907
epoch 232 - data_loss(MSE): 0.354080 | reg_loss: 0.000631 | total: 0.354711
epoch 233 - data_loss(MSE): 0.332141 | reg_loss: 0.000633 | total: 0.332775
epoch 234 - data_loss(MSE): 0.350684 | reg_loss: 0.000631 | total: 0.351315
epoch 235 - data_loss(MSE): 0.330189 | reg_loss: 0.000633 | total: 0.330822
epoch 236 - data_loss(MSE): 0.346883 | reg_loss: 0.000631 | total: 0.347514
epoch 237 - data_loss(MSE): 0.327692 | reg_loss: 0.000633 | total: 0.328325
epoch 238 - data_loss(MSE): 0.342286 | reg_loss: 0.000631 | total: 0.342917
epoch 239 - data_loss(MSE): 0.324336 | reg_loss: 0.000633 | total: 0.324969
epoch 240 - data_loss(MSE): 0.337470 | reg_loss: 0.000631 | total: 0.338101
epoch 241 - data_loss(MSE): 0.321864 | reg_loss: 0.000633 | total: 0.322498
epoch 242 - data_loss(MSE): 0.334068 | reg_loss: 0.000631 | total: 0.334699
epoch 243 - data_loss(MSE): 0.320795 | reg_loss: 0.000633 | total: 0.321428
epoch 244 - data_loss(MSE): 0.333289 | reg_loss: 0.000631 | total: 0.333920
epoch 245 - data_loss(MSE): 0.320440 | reg_loss: 0.000633 | total: 0.321074
epoch 246 - data_loss(MSE): 0.333567 | reg_loss: 0.000631 | total: 0.334198
epoch 247 - data_loss(MSE): 0.320224 | reg_loss: 0.000633 | total: 0.320857
epoch 248 - data_loss(MSE): 0.332782 | reg_loss: 0.000631 | total: 0.333414
epoch 249 - data_loss(MSE): 0.318991 | reg_loss: 0.000633 | total: 0.319624
epoch 250 - data_loss(MSE): 0.331488 | reg_loss: 0.000631 | total: 0.332119
epoch 251 - data_loss(MSE): 0.318187 | reg_loss: 0.000633 | total: 0.318820
epoch 252 - data_loss(MSE): 0.331116 | reg_loss: 0.000631 | total: 0.331747
epoch 253 - data_loss(MSE): 0.317767 | reg_loss: 0.000633 | total: 0.318400
epoch 254 - data_loss(MSE): 0.330763 | reg_loss: 0.000631 | total: 0.331394
epoch 255 - data_loss(MSE): 0.317480 | reg_loss: 0.000633 | total: 0.318113
epoch 256 - data_loss(MSE): 0.330775 | reg_loss: 0.000631 | total: 0.331406
epoch 257 - data_loss(MSE): 0.318820 | reg_loss: 0.000633 | total: 0.319453
epoch 258 - data_loss(MSE): 0.332935 | reg_loss: 0.000631 | total: 0.333566
epoch 259 - data_loss(MSE): 0.319622 | reg_loss: 0.000633 | total: 0.320255
epoch 260 - data_loss(MSE): 0.334398 | reg_loss: 0.000631 | total: 0.335029
epoch 261 - data_loss(MSE): 0.319919 | reg_loss: 0.000633 | total: 0.320552
epoch 262 - data_loss(MSE): 0.335176 | reg_loss: 0.000631 | total: 0.335808
epoch 263 - data_loss(MSE): 0.319827 | reg_loss: 0.000633 | total: 0.320460
epoch 264 - data_loss(MSE): 0.335943 | reg_loss: 0.000631 | total: 0.336574

In [11]:
X_test =np.asarray( X_test.T) 
prediction = nn.predict(X_test) # making predictions on X_test

In [12]:
y_test = np.asarray(y_test).reshape(1, -1)
nn.meansquarederror(prediction, y_test) # checking the accuracy of predictions on test data

0.5716184529706739